backend = "glx";
#vsync = false;

opacity-rule = [
      "98:class_g = 'kitty' && focused",
      "100:class_g = 'kitty' && !focused",
      "70:class_g = 'st-256color' && focused",
      "100:class_g = 'st-256color' && !focused"
];
