#!/bin/bash

# Prompt the user to enter the desired color temperature in Kelvin using dmenu
kelvin=$(echo "" | dmenu -p "Enter the desired color temperature in Kelvin:")

# Set the color temperature using redshift
redshift -m randr -PO "$kelvin"
