#!/bin/bash

if xinput list | grep -q "Logitech USB Receiver"; then

xinput set-prop "Logitech USB Receiver" "libinput Scroll Method Enabled" 0, 0, 0
# Send notification
    notify-send "Logitech Mouse" "Scrolling disabled."
else
    notify-send "Logitech mouse not found or no slave pointer found."
fi
