# Fonts
font_family      Hack Nerd Font Mono
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
# bold_italic_font CodeNewRomanNerdFontMono-BoldItalic

font_size 11
# window_padding_width 10

enable_audio_bell no
confirm_os_window_close 0

background            #282828
color2                #99C88C
color3                #91231c
